config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
  enum status: { pending: 0, comfirmed: 1 }
  belongs_to :user
  validates_presence_of :user_id, :status, :start_date

  after_initialize :set_dafaults

  private

  def set_dafaults
    self.start_date ||= (Date.today - 6.days)
  end
end

app/models/employee.rb
class Employee < User
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user

  validates_presence_of :date, :rationale, :overtime_request
  validates_numericality_of :overtime_request, greater_than: 0.0

  scope :posts_by, -> (user) { where(user_id: user.id) }

  after_save :update_audit_log

  private

  def update_audit_log
    audit_log = AuditLog.where(user_id: self.user_id, start_date: (self.date - 7.days..self.date)).last
    audit_log.comfirmed! if audit_log
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :audit_logs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :first_name, :last_name, :phone

  PHONE_REGEX = /\A[0-9]*\Z/
  validates_format_of :phone, with: PHONE_REGEX
  validates :phone, length: { is: 10 }

  def fullname
    last_name.upcase + "," + " " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin
    before_action :authenticate_user!

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access to this page"
        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def admin_types
		['AdminUser']
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/audit_logs_controller.rb
class AuditLogsController < ApplicationController
  def index
    @audit_logs = AuditLog.page(params[:page]).per(10)
    authorize @audit_logs
  end

  def confirm
		audit_log = AuditLog.find(params[:id])
		authorize audit_log
		audit_log.comfirmed!
		redirect_to root_path, notice: "Thank you, your confirmation has been successfully made."
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_post, only: [:show, :edit, :update, :destroy, :approve]
  def index
    @posts = Post.posts_by(current_user).page(params[:page]).per(10)
  end

  def approve
    authorize @post
    @post.approved!
    redirect_to root_path, notice: "The post has been approved"
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post, notice: 'Post was created'
    else
      render :new
    end
  end

  def show; end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update_attributes(post_params)
      redirect_to @post, notice: 'Post was updated'
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path, notice: "Your post was deleted"
  end

  private

  def post_params
    params.require(:post).permit(:date, :rationale, :status, :overtime_request)
  end

  def current_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
    if admin_types.include? current_user.type
      @pending_approvals = Post.submitted
      @recent_audit_items = AuditLog.last(10)
    else
      @pending_audit_confirmations = current_user.audit_logs.pending
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_types
		['AdminUser']
  end

  def active?(path)
    'active' if current_page?(path)
  end

  def status_label status
    status_span_generator status
  end

  private

  def status_span_generator status
    case status
    when 'submitted'
      content_tag(:span, status.titleize, class: 'label label-primary')
    when 'approved'
      content_tag(:span, status.titleize, class: 'label label-success')
    when 'rejected'
      content_tag(:span, status.titleize, class: 'label label-danger')
    when 'pending'
      content_tag(:span, status.titleize, class: 'label label-primary')
    when 'comfirmed'
      content_tag(:span, status.titleize, class: 'label label-success')
    end
  end
end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/audit_logs/_audit_log.html.erb
<tr>
	<td>
		<%= audit_log.id %>
	</td>
	<td>
		<%= audit_log.user.fullname %>
	</td>
	<td>
		<%= audit_log.start_date %>
	</td>
	<td>
		<%= audit_log.end_date %>
	</td>
	<td>
		<%= status_label audit_log.status %>
	</td>
</tr>

app/views/audit_logs/index.html.erb
<h1>Audit Log Dashboard</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Employee
			</th>
			<th>
				Week Starting
			</th>
			<th>
				Confirmed At
			</th>
			<th>
				Status
			</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody id="audit_logs">
		<%= render @audit_logs %>
	</tbody>
</table>
<div id="paginator">
	<%= paginate @audit_logs, remote: true %>
</div>

app/views/audit_logs/index.js.erb
$('#audit_logs').html('<%= escape_javascript render(@audit_logs) %>');
$('#paginator').html('<%= escape_javascript(paginate(@audit_logs, remote: true).to_s) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Overtime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= render 'shared/nav' %>
			<%= yield %>
		</div>
	</div>
</div>
<%= render 'shared/alerts' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Overtime App Notification", sticky: false) %>
    <% end %>
  <% end %>
  <div class="form-group">
  	<%= f.label :overtime_request, class: "col-sm-2 control-label" %>
  	<%= f.text_field :overtime_request, class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label :date, class: "col-sm-2 control-label" %>
  	<%= f.date_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label :rationale, class: "col-sm-2 control-label" %>
  	<%= f.text_area :rationale, class: "form-control" %>
  </div>
  <%= render partial: 'status', locals: {f: f} if current_user.type == "AdminUser" %>
  <%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.id %>
  </td>
  <td>
    <%= post.overtime_request %>
  </td>
  <td>
    <%= post.date %>
  </td>
  <td>
    <%= post.user.fullname %>
  </td>
  <td>
    <%= link_to truncate(post.rationale), post %>
  </td>
  <td>
    <%= status_label post.status %>
  </td>
  <td>
    <%= link_to '', edit_post_path(post), class: 'glyphicon glyphicon-pencil index-icons', id: "edit_#{ post.id }" if policy(post).update? %>
  </td>
  <td>
    <%= link_to '', post_path(post), method: :delete, id: "delete_#{ post.id }", class: 'glyphicon glyphicon-trash index-icons', data: { confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.radio_button :status, 'submitted' %>
  <%= f.label :status, 'Submitted' %>

  <%= f.radio_button :status, 'approved' %>
  <%= f.label :status, 'Approved' %>

  <%= f.radio_button :status, 'rejected' %>
  <%= f.label :status, 'Rejected' %>
</div>

app/views/posts/edit.html.erb
<h1>Edit</h1>
<%= render 'form'%>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
				#
			</th>
			<th>
				Overtime Request
			</th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Rationale
			</th>
			<th>
				Status
			</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody id="posts">
		<%= render @posts %>
	</tbody>
</table>
<div id="paginator">
	<%= paginate @posts, remote: true %>
</div>

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<h1>Create new post</h1>
<%= render 'form'%>

app/views/posts/show.html.erb
<div>
	<h2><%= @post.rationale %></h2>
</div>

<div class="well">
	<div>
		<h3><span>Overtime Amount Requested:</span> <%= @post.overtime_request %></h3>
	</div>

	<div>
		<h3><span>Employee:</span> <%= @post.user.fullname %></h3>
	</div>

	<div>
		<h3><span>Date:</span> <%= @post.date %></h3>
	</div>

	<div>
		<h3><span>Current Stage of Approval:</span> <%= @post.status %></h3>
	</div>
</div>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' if policy(@post).update? %>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false) %>
<% elsif flash[:error] %>
	<%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false) %>
<% else %>
	<%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false) %>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class="<%= active?(audit_logs_path) %>">
	<%= link_to "Audit Log", audit_logs_path %>
</li>

app/views/shared/_nav.html.erb
<div class='logo'>
	<h1>Time Tracker</h1>
</div>

<!-- TODO -->
<% if current_user %>
	<ul class="custom-nav nav nav-tabs">
		<li class="<%= active?(root_path) %>">
			<%= link_to "Home", root_path %>
		</li>
		<li class="<%= active?(posts_path) %>">
			<%= link_to "Time Entries", posts_path %>
		</li>

		<!-- TODO: possibly refactor -->
		<%= render 'shared/audit_log_tab' if policy(AuditLog).index? %>

		<li class="<%= active?(new_post_path) %>">
			<%= link_to "Request overtime", new_post_path, id: 'new_post_from_nav' %>
		</li>
		<li class="dropdown pull-right">
			 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
			<ul class="dropdown-menu">

				<!-- TODO -->
				<% if current_user.try(:type) == 'AdminUser' %>
				<li>
					<%= link_to "Admin Dashboard", admin_root_path %>
				</li>
				<li class="divider"></li>
				<% end %>
				<!-- TODO -->

				<li>
					<%= link_to "Logout", destroy_user_session_path, method: :delete %>
				</li>
			</ul>
		</li>
	</ul>
<% end %>
<!-- TODO -->